### ISSUE TITLE
Problem with New Wox

### ISSUE THREAD

**Issue by benyaminl** [lances101/Wox.Plugin.SimpleClock#5]
Please open new issue in: https://github.com/Wox-launcher/Wox/issues/new
1. upload log file: C:\Users\Ben\AppData\Roaming\Wox\Logs\1.3.424\2017-04-16.txt
2. copy below exception message

Wox version: 1.3.424
OS Version: Microsoft Windows NT 6.1.7601 Service Pack 1
IntPtr Length: 8
x64: True

Python Path: C:\Users\Ben\AppData\Local\Programs\Python\Python35-32\pythonw.exe
Everything SDK Path: C:\Users\Ben\AppData\Roaming\Wox\Settings\Plugins\Wox.Plugin.Everything\EverythingSDK\x64\Everything.dll
Date: 04/16/2017 16:16:44
Exception:
Wox.Plugin.SimpleClock
System.TypeLoadException
Could not load type 'Wox.Infrastructure.Storage.Storage`1' from assembly 'Wox.Infrastructure, Version=1.3.424.0, Culture=neutral, PublicKeyToken=null'.
   at Wox.Plugin.SimpleClock.Commands.Alarm.AlarmTimerCommand.CommandExecution(List`1 args)
   at Wox.Plugin.Boromak.CommandHandlerBase.Execute(List`1 args) in C:\Users\Boris\Documents\SourceControl\Wox\Wox.Plugin.SimpleClock\Wox.Plugin.Boromak\Wox.Plugin.Boromak\CommandHandlerBase.cs:line 166
   at Wox.ViewModel.MainViewModel.<InitializeKeyCommands>b__16_6(Object index) in C:\projects\wox\Wox\ViewModel\MainViewModel.cs:line 146
   at System.Windows.Input.CommandManager.TranslateInput(IInputElement targetElement, InputEventArgs inputEventArgs)
   at System.Windows.UIElement.OnKeyDownThunk(Object sender, KeyEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndKeyboardInputProvider.ProcessKeyAction(MSG& msg, Boolean& handled)
   at System.Windows.Interop.HwndSource.CriticalTranslateAccelerator(MSG& msg, ModifierKeys modifiers)
   at System.Windows.Interop.HwndSource.OnPreprocessMessage(Object param)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by benyaminl** [comment]
any Ideas? No Update?

**Comment by lances101** [comment]
@benyaminl, I now have some free time now, but the [main Wox repo](https://github.com/Wox-launcher/Wox) has some critical bugs that need to be fixed first. I will update as soon as Wox gets more stable.

**Comment by Koriit** [comment]
Hello, do you have any plans and/or time to fix the compatibility issue? :)

**Comment by magicdmer** [comment]
This question need rebuild with newest wox plugin library, and all will be ok

**Comment by jeremymeyers** [comment]
@lances101 Hoping for a rebuild!
